#:schema ../node_modules/wrangler/config-schema.json

name = "nuinui-api"
main = "index.ts"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "nuinui"
database_id = "ae01e627-dfab-48da-b8f4-b3d688ca0a4b"
